


CREATE TABLE PAIS (
    id_pais NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 9 INCREMENT BY 3),
    nom_pais VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_pais PRIMARY KEY (id_pais)
);

CREATE TABLE CIUDAD (
    id_ciudad NUMBER,
    nom_ciudad VARCHAR2(60) NOT NULL,
    id_pais NUMBER NOT NULL,
    CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad),
    CONSTRAINT fk_ciudad_pais FOREIGN KEY (id_pais)
        REFERENCES PAIS(id_pais)
);

CREATE TABLE SUCURSAL (
    id_sucursal CHAR(3),
    nom_sucursal VARCHAR2(60) NOT NULL,
    calle VARCHAR2(80),
    num_calle NUMBER(6),
    id_ciudad NUMBER NOT NULL,
    CONSTRAINT pk_sucursal PRIMARY KEY (id_sucursal),
    CONSTRAINT fk_sucursal_ciudad FOREIGN KEY (id_ciudad)
        REFERENCES CIUDAD(id_ciudad)
);

CREATE TABLE MARCA (
    id_marca NUMBER,
    nom_marca VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_marca PRIMARY KEY (id_marca)
);

CREATE TABLE MODELO (
    id_modelo NUMBER,
    nom_modelo VARCHAR2(50) NOT NULL,
    id_marca NUMBER NOT NULL,
    CONSTRAINT pk_modelo PRIMARY KEY (id_modelo),
    CONSTRAINT fk_modelo_marca FOREIGN KEY (id_marca)
        REFERENCES MARCA(id_marca)
);

CREATE TABLE TIPO_AUTOMOVIL (
    id_tipo_auto NUMBER,
    descripcion VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_tipo_auto PRIMARY KEY (id_tipo_auto)
);

CREATE TABLE CLIENTE (
    rut NUMBER(9),
    dv CHAR(1) NOT NULL,
    pnombre VARCHAR2(30) NOT NULL,
    snombre VARCHAR2(30),
    apaterno VARCHAR2(30) NOT NULL,
    amaterno VARCHAR2(30),
    email VARCHAR2(100),
    telefono VARCHAR2(20),
    tipo_cliente VARCHAR2(10) NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (rut),
    CONSTRAINT ck_cliente_dv CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K')),
    CONSTRAINT ck_cliente_tipo CHECK (tipo_cliente IN ('ESTANDAR','PREMIUM'))
);

CREATE TABLE AUTOMOVIL (
    patente VARCHAR2(10),
    rut_cliente NUMBER(9) NOT NULL,
    id_modelo NUMBER NOT NULL,
    id_tipo_auto NUMBER NOT NULL,
    anio NUMBER(4),
    CONSTRAINT pk_automovil PRIMARY KEY (patente),
    CONSTRAINT fk_auto_cliente FOREIGN KEY (rut_cliente)
        REFERENCES CLIENTE(rut),
    CONSTRAINT fk_auto_modelo FOREIGN KEY (id_modelo)
        REFERENCES MODELO(id_modelo),
    CONSTRAINT fk_auto_tipo FOREIGN KEY (id_tipo_auto)
        REFERENCES TIPO_AUTOMOVIL(id_tipo_auto)
);

CREATE TABLE MECANICO (
    cod_mecanico NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 460 INCREMENT BY 7),
    pnombre VARCHAR2(30) NOT NULL,
    snombre VARCHAR2(30),
    apaterno VARCHAR2(30) NOT NULL,
    amaterno VARCHAR2(30),
    sueldo NUMBER(10) NOT NULL,
    bono_jefatura NUMBER(10),
    monto_impuestos NUMBER(10) NOT NULL,
    cod_supervisor NUMBER,
    CONSTRAINT pk_mecanico PRIMARY KEY (cod_mecanico),
    CONSTRAINT fk_mec_supervisor FOREIGN KEY (cod_supervisor)
        REFERENCES MECANICO(cod_mecanico),
    CONSTRAINT ck_mec_sueldo CHECK (sueldo >= 510000)
);

CREATE TABLE SERVICIO (
    id_servicio NUMBER,
    descripcion VARCHAR2(100) NOT NULL,
    costo NUMBER(10) NOT NULL,
    CONSTRAINT pk_servicio PRIMARY KEY (id_servicio)
);

CREATE TABLE MANTENCION (
    num_mantencion NUMBER,
    id_sucursal CHAR(3),
    patente VARCHAR2(10) NOT NULL,
    cod_mecanico NUMBER NOT NULL,
    fecha_llegada DATE NOT NULL,
    fecha_salida DATE,
    costo_total NUMBER,
    estado VARCHAR2(15),
    CONSTRAINT pk_mantencion PRIMARY KEY (num_mantencion),
    CONSTRAINT fk_mant_sucursal FOREIGN KEY (id_sucursal)
        REFERENCES SUCURSAL(id_sucursal),
    CONSTRAINT fk_mant_auto FOREIGN KEY (patente)
        REFERENCES AUTOMOVIL(patente),
    CONSTRAINT fk_mant_mecanico FOREIGN KEY (cod_mecanico)
        REFERENCES MECANICO(cod_mecanico)
);

CREATE TABLE DETALLE_SERVICIO (
    num_mantencion NUMBER,
    id_sucursal CHAR(3),
    id_servicio NUMBER,
    cantidad NUMBER(5) NOT NULL,
    CONSTRAINT pk_det_serv PRIMARY KEY (num_mantencion, id_sucursal, id_servicio),
    CONSTRAINT fk_det_servicio FOREIGN KEY (id_servicio)
        REFERENCES SERVICIO(id_servicio)
);

CREATE SEQUENCE seq_servicio START WITH 400 INCREMENT BY 2;
CREATE SEQUENCE seq_ciudad START WITH 165 INCREMENT BY 5;

ALTER TABLE MANTENCION DROP COLUMN costo_total;

ALTER TABLE MANTENCION DROP CONSTRAINT pk_mantencion;

ALTER TABLE MANTENCION ADD CONSTRAINT pk_mantencion
PRIMARY KEY (num_mantencion, id_sucursal);

ALTER TABLE DETALLE_SERVICIO ADD CONSTRAINT fk_det_mant
FOREIGN KEY (num_mantencion, id_sucursal)
REFERENCES MANTENCION(num_mantencion, id_sucursal);

ALTER TABLE CLIENTE ADD CONSTRAINT un_cliente_email UNIQUE (email);

ALTER TABLE MANTENCION ADD CONSTRAINT ck_mant_estado
CHECK (estado IN ('Reserva','Ingresado','Entregado','Anulado'));

SELECT
    cod_mecanico AS id_mecanico,
    pnombre || ' ' || apaterno AS nombre_mecanico,
    sueldo AS salario,
    monto_impuestos AS impuesto_actual,
    ROUND(monto_impuestos * 0.8) AS impuesto_rebajado,
    sueldo - ROUND(monto_impuestos * 0.8) AS sueldo_con_rebaja_impuestos
FROM MECANICO
WHERE bono_jefatura IS NULL
  AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, apaterno ASC;

SELECT
    cod_mecanico AS identificador,
    pnombre || ' ' || snombre || ' ' || apaterno AS mecanico,
    sueldo AS salario_actual,
    ROUND(sueldo * 0.05) AS ajuste,
    sueldo + ROUND(sueldo * 0.05) AS sueldo_reajustado
FROM MECANICO
WHERE (sueldo BETWEEN 600000 AND 900000)
   OR cod_supervisor IS NULL
ORDER BY sueldo ASC, mecanico DESC;





